// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Position, PlayerStatsResponse } from "./../../interfaces/Types.sol";

/**
 * @title IGameSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGameSystem {
  function start(Position[] calldata ethersPosition_) external;

  function buyBullets(uint amount_) external payable;

  function getGameData() external view returns (PlayerStatsResponse memory);

  function registerAction(
    uint[] calldata removeEtherIds_,
    uint shotBulletsAmount_,
    Position calldata newPlayerPosition_
  ) external;
}
