// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Bullets, BulletsTableId } from "./tables/Bullets.sol";
import { PlayerPosition, PlayerPositionData, PlayerPositionTableId } from "./tables/PlayerPosition.sol";
import { Ethers, EthersData, EthersTableId } from "./tables/Ethers.sol";
import { EthersArrangement, EthersArrangementData, EthersArrangementTableId } from "./tables/EthersArrangement.sol";
